theme: jekyll-theme-minimal
title: [Gahl Shemy's Website]
title_separator: |
description: []
minimal_mistakes_skin: sunrise 
show_date: true 
logo: "/assets/images/github.jpg"

markdown: kramdown
kramdown:
    math_engine: katex
